version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-primordial@duck2025}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-primordial_duck_operation}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pdo-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --max_connections=50
      --innodb_buffer_pool_size=256M
      --innodb_log_file_size=64M
      --innodb_flush_log_at_trx_commit=2
      --query_cache_size=0
      --performance_schema=OFF
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD:-primordial@duck2025}"]
      timeout: 20s
      retries: 10
      interval: 15s
      start_period: 60s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.4'
          memory: 600M
        reservations:
          cpus: '0.2'
          memory: 400M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  api:
    image: ghcr.io/daniellebassetto/primordial-duck-operation/api:latest
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=${MYSQL_DATABASE:-primordial_duck_operation};User=root;Password=${MYSQL_ROOT_PASSWORD:-primordial@duck2025};
      - DOTNET_GCHeapHardLimit=0x20000000
    networks:
      - pdo-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.4'
          memory: 700M
        reservations:
          cpus: '0.2'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ghcr.io/daniellebassetto/primordial-duck-operation/frontend:latest
    ports:
      - "80:80"
    networks:
      - pdo-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback

networks:
  pdo-network:
    driver: overlay
    attachable: true

volumes:
  mysql_data:
    driver: local
